create table paises (
  pais_id bigint generated by default as identity primary key,
  pais_nome text not null unique,
  codigo_pais text,
  continente text,
  idioma_principal text
);

create table localizacoes (
  localizacao_id bigint generated by default as identity primary key,
  regiao text,
  cidade text,
  clima text,
  temperatura_media_c numeric,
  proximidade_agua text,
  pais_id bigint not null references paises(pais_id)
);

create table empresas (
  empresa_id bigint generated by default as identity primary key,
  empresa_nome text not null unique
);

create table ias (
  ia_id bigint generated by default as identity primary key,
  ia_nome text not null,
  versao_ia text,
  tipo_modelo text,
  empresa_id bigint references empresas(empresa_id)
);

create table usos_ia (
  uso_id bigint generated by default as identity primary key,
  uso_principal text,
  observacao text
);

create table infraestrutura (
  infraestrutura_id bigint generated by default as identity primary key,
  tipo_data_center text,
  tipo_resfriamento text,
  fonte_energia text,
  ano_instalacao integer,
  status text,
  numero_servidores_estimado integer,
  custo_anual_mi_usd numeric
);

create table metricas_uso (
  metrica_id bigint generated by default as identity primary key,
  usuarios_milhoes numeric,
  interacoes_dia_mi numeric,
  latencia_media_ms numeric,
  pico_uso text,
  crescimento_anual numeric
);

create table impacto_ambiental (
  impacto_id bigint generated by default as identity primary key,
  consumo_agua_milhoes_l_ano numeric,
  regulamentacao_ambiental text,
  reuso_agua text
);

create table atividade_ia_pais (
  atividade_id bigint generated by default as identity primary key,
  pais_id bigint not null references paises(pais_id),
  ia_id bigint not null references ias(ia_id),
  localizacao_id bigint references localizacoes(localizacao_id),
  uso_id bigint references usos_ia(uso_id),
  infraestrutura_id bigint references infraestrutura(infraestrutura_id),
  metrica_id bigint references metricas_uso(metrica_id),
  impacto_id bigint references impacto_ambiental(impacto_id)
);
